[package]
name = "coroutine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 最后肯定要参考https://github.com/hnes/libaco来自己实现协程的上下文切换
context = "2.1.0"