[package]
name = "generator"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.119"

[target."cfg(windows)".dependencies.kernel32-sys]
version = "0.2.2"
[target."cfg(windows)".dependencies.winapi]
version = "0.2.2"

[build-dependencies]
cc = "1.0.73"
rustversion = "1.0.6"